spring:
    profiles:
        active: dev
        
---

spring:
    profiles: dev
    application:
        nama: springcloud-config-dev
        
---

spring:
    profiles: test
    application:
        nama: springcloud-config-test
        